"""Editable training knobs for the CIFAR-10 CNN harness."""

SEED = 17
DEVICE = "auto"
DETERMINISTIC = True

TRAIN_EXAMPLES_PER_CLASS = 1000
TEST_EXAMPLES_PER_CLASS = 200

EPOCHS = 8
BATCH_SIZE = 128
LEARNING_RATE = 0.001
WEIGHT_DECAY = 0.0001
MOMENTUM = 0.9

DROPOUT = 0.25
USE_AUGMENTATION = False
NUM_WORKERS = 0

TARGET_ACCURACY = 0.70

