"""Operating brief generation for harness optimization runs."""

from __future__ import annotations

from pathlib import Path

from ralph_loop_optimizer.config import OptimizerConfig
from ralph_loop_optimizer.harness import HarnessSummary, assert_git_repository


BRIEF_FILENAME = "RALPH_LOOP.md"


class BriefError(ValueError):
    """Raised when an operating brief cannot be written."""


def build_operating_brief(
    config: OptimizerConfig,
    summary: HarnessSummary,
) -> str:
    worktree_status = "dirty" if summary.worktree_status.is_dirty else "clean"
    lines = [
        "# Ralph Loop Operating Brief",
        "",
        "Generated by `ralph-loop init`. Review and edit this file before "
        "starting optimization.",
        "",
        "## Optimization Goal",
        "",
        config.goal.strip(),
        "",
        "## Harness Snapshot",
        "",
        f"- Repository: `{summary.repo_path}`",
        f"- Worktree status at initialization: {worktree_status}",
        f"- Selected backend: `{config.backend}`",
        f"- Maximum iterations: {config.max_iterations}",
        f"- Run artifact directory: `{config.run_artifact_dir.as_posix()}`",
        "",
    ]

    if summary.worktree_status.entries:
        lines.extend(
            [
                "Uncommitted worktree entries seen during initialization:",
                "",
                *_format_bullets(summary.worktree_status.entries),
                "",
            ]
        )

    lines.extend(
        [
            "## Evaluation",
            "",
            "- Configured evaluation command: "
            f"{_format_optional_command(config.evaluation_command)}",
            "",
            "Candidate evaluation files:",
            "",
            *_format_paths(summary.candidate_evaluation_files),
            "",
            "## Relevant Harness Files",
            "",
            "Candidate documentation:",
            "",
            *_format_paths(summary.candidate_docs),
            "",
            "Candidate setup files:",
            "",
            *_format_paths(summary.candidate_setup_files),
            "",
            "Candidate test files:",
            "",
            *_format_paths(summary.candidate_test_files),
            "",
            "Agent instruction files:",
            "",
            *_format_paths(summary.instruction_files),
            "",
            "## Expected Iteration Process",
            "",
            "1. Read this operating brief and the relevant harness instructions.",
            "2. Read prior iteration artifacts and lessons when they exist.",
            "3. Ask the selected coding backend to attempt one improvement.",
            "4. Run or request the harness evaluation.",
            "5. Save prompts, backend output, evaluation output, diffs, and lessons.",
            "6. Commit the completed experiment in the harness Git repository.",
            "7. Decide whether to continue based on results and configured limits.",
            "",
            "## Assumptions And Uncertainties",
            "",
            "- Ralph Loop Optimizer owns orchestration only; the harness owns "
            "domain behavior and scoring.",
            "- Candidate files above were inferred from file names and repository "
            "layout, not from executing the harness.",
            "- Evaluation output may use any format that is visible and useful for "
            "comparison across iterations.",
            "- Confirm any uncommitted harness changes before starting optimization.",
            "",
            "## Questions For The User",
            "",
            "- Is the optimization goal above accurate?",
            "- Is the configured evaluation command correct and complete?",
            "- Which files or workflows are safe for the optimizer to change?",
            "- Are there files, commands, or behaviors that must not be changed?",
            "- What result or stopping condition should count as good enough?",
            "",
            "## Start Boundary",
            "",
            "Optimization must not start until the user explicitly approves a run. "
            "Initialization only creates or updates this operating brief.",
            "",
        ]
    )
    return "\n".join(lines)


def write_operating_brief(
    repo_path: Path,
    content: str,
    overwrite: bool = False,
) -> Path:
    repo_path = repo_path.expanduser().resolve()
    assert_git_repository(repo_path)
    brief_path = repo_path / BRIEF_FILENAME

    if brief_path.exists() and not overwrite:
        raise BriefError(
            f"{BRIEF_FILENAME} already exists; pass overwrite=True to replace it"
        )

    brief_path.write_text(_ensure_trailing_newline(content), encoding="utf-8")
    return brief_path


def brief_exists(repo_path: Path) -> bool:
    return (repo_path.expanduser().resolve() / BRIEF_FILENAME).exists()


def _format_optional_command(command: str | None) -> str:
    if command is None:
        return "not provided"
    return f"`{command.strip()}`"


def _format_paths(paths: list[Path]) -> list[str]:
    if not paths:
        return ["- None found."]
    return [f"- `{path.as_posix()}`" for path in paths]


def _format_bullets(values: tuple[str, ...]) -> list[str]:
    return [f"- `{value}`" for value in values]


def _ensure_trailing_newline(content: str) -> str:
    if content.endswith("\n"):
        return content
    return f"{content}\n"
