"""Operating brief generation for harness optimization runs."""

from __future__ import annotations

from pathlib import Path

from ralph_loop_optimizer.config import OptimizerConfig
from ralph_loop_optimizer.harness import HarnessSummary, assert_git_repository


BRIEF_FILENAME = "RALPH_LOOP.md"


class BriefError(ValueError):
    """Raised when an operating brief cannot be written."""


def build_operating_brief(
    config: OptimizerConfig,
    _summary: HarnessSummary,
) -> str:
    lines = [
        "# Ralph Loop Operating Brief",
        "",
        "Generated by `ralph-loop init`. Review and edit this file before "
        "starting optimization.",
        "",
        "## Optimization Goal",
        "",
        config.goal.strip(),
        "",
        "## Harness Reference Files",
        "",
        "To be completed during init review or by the user.",
        "",
        "List only files that are actually relevant after inspecting the "
        "harness. For each file, include why it matters. Do not copy full "
        "file contents here.",
        "",
        "- `<path>`: `<why this file matters>`",
        "",
        "## Working Environment",
        "",
        "To be completed during init review or by the user.",
        "",
        "- Dependency or environment files to inspect: `<fill in>`",
        "- Setup or installation command, if needed: `<fill in>`",
        "- Command wrapper for local checks and evaluation: `<fill in>`",
        "- Environment assumptions or unresolved questions: `<fill in>`",
        "",
        "## File Modification Scope",
        "",
        "To be completed during init review or by the user.",
        "",
        "- Allowed files or directories to change: `<fill in>`",
        "- Files, commands, outputs, or behaviors that must not be changed: "
        "`<fill in>`",
        "- Evaluation/scoring behavior constraints: `<fill in>`",
        "",
        "## AI Behavior Requirements",
        "",
        "To be completed during init review or by the user.",
        "",
        "- Read relevant harness files before editing.",
        "- Make one focused improvement per iteration, tied directly to the "
        "optimization goal.",
        "- Preserve evaluation/scoring semantics unless explicitly allowed.",
        "- Use prior lessons and evaluation evidence when they are provided.",
        "- Do not invent domain assumptions that are not supported by the "
        "harness files, this brief, or the user goal.",
        "- Leave unrelated files and formatting alone.",
        "",
        "## Open Questions",
        "",
        "- `<question or uncertainty to resolve before running optimization>`",
        "",
    ]
    return "\n".join(lines)


def write_operating_brief(
    repo_path: Path,
    content: str,
    overwrite: bool = False,
) -> Path:
    repo_path = repo_path.expanduser().resolve()
    assert_git_repository(repo_path)
    brief_path = repo_path / BRIEF_FILENAME

    if brief_path.is_symlink():
        raise BriefError(f"{BRIEF_FILENAME} must not be a symlink")

    if brief_path.exists() and not overwrite:
        raise BriefError(
            f"{BRIEF_FILENAME} already exists; pass overwrite=True to replace it"
        )

    brief_path.write_text(_ensure_trailing_newline(content), encoding="utf-8")
    return brief_path


def brief_exists(repo_path: Path) -> bool:
    return (repo_path.expanduser().resolve() / BRIEF_FILENAME).exists()


def _ensure_trailing_newline(content: str) -> str:
    if content.endswith("\n"):
        return content
    return f"{content}\n"
